### ISSUE TITLE
fetchOHLCV causing JsonReaderException

### ISSUE THREAD

**Issue by jimeney** [Stock84-dev/CCXTSharp#1]
Example call:
long dt = DateTimeOffset.UtcNow.AddHours(-1).ToUnixTimeMilliseconds();
List<Candlestick> c = await ccxtAPI.FetchOHLCV("coinbasepro", "BTC/USD", Timeframe.min1,dt);

Throws error:
Newtonsoft.Json.JsonReaderException: 'Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1.'

ccxtApi.ShowPipeData = true shows OHLCV data being returned.

**Comment by Stock84-dev** [comment]
Fixed in 3fc4312ca67a4e32455e95d8ae4e3fffda63a347. Sorry that you waited for so long.
